### ISSUE TITLE
Sanitize Metric Names

### ISSUE THREAD

**Issue by jeschkies** [kamon-io/kamon-jmx#7]
We used to get this error

```
[info] [ERROR] [12/12/2017 12:32:30.755] [kamon-akka.actor.default-dispatcher-2] [akka://kamon/user/kamon-jmx-reporter/kamon-jmx-actor] Invalid character ‘:’ in value part of property
[info] javax.management.MalformedObjectNameException: Invalid character ‘:’ in value part of property
[info] 	at javax.management.ObjectName.construct(ObjectName.java:618)
[info] 	at javax.management.ObjectName.<init>(ObjectName.java:1382)
[info] 	at kamon.jmx.MBeanManager$.createOrUpdateMBean(JMXReporterActor.scala:135)
[info] 	at kamon.jmx.JMXReporterActor$.kamon$jmx$JMXReporterActor$$updateCounterMetrics(JMXReporterActor.scala:183)
[info] 	at kamon.jmx.JMXReporterActor$$anonfun$receive$1.$anonfun$applyOrElse$4(JMXReporterActor.scala:202)
[info] 	at kamon.jmx.JMXReporterActor$$anonfun$receive$1.$anonfun$applyOrElse$4$adapted(JMXReporterActor.scala:196)
[info] 	at scala.collection.TraversableLike$WithFilter.$anonfun$foreach$1(TraversableLike.scala:789)
[info] 	at scala.collection.immutable.Map$Map1.foreach(Map.scala:120)
[info] 	at scala.collection.TraversableLike$WithFilter.foreach(TraversableLike.scala:788)
[info] 	at kamon.jmx.JMXReporterActor$$anonfun$receive$1.$anonfun$applyOrElse$2(JMXReporterActor.scala:196)
[info] 	at kamon.jmx.JMXReporterActor$$anonfun$receive$1.$anonfun$applyOrElse$2$adapted(JMXReporterActor.scala:195)
[info] 	at scala.collection.TraversableLike$WithFilter.$anonfun$foreach$1(TraversableLike.scala:789)
[info] 	at scala.collection.immutable.HashMap$HashMap1.foreach(HashMap.scala:231)
[info] 	at scala.collection.immutable.HashMap$HashTrieMap.foreach(HashMap.scala:462)
[info] 	at scala.collection.immutable.HashMap$HashTrieMap.foreach(HashMap.scala:462)
[info] 	at scala.collection.TraversableLike$WithFilter.foreach(TraversableLike.scala:788)
[info] 	at kamon.jmx.JMXReporterActor$$anonfun$receive$1.applyOrElse(JMXReporterActor.scala:195)
[info] 	at akka.actor.Actor.aroundReceive(Actor.scala:502)
[info] 	at akka.actor.Actor.aroundReceive$(Actor.scala:500)
[info] 	at kamon.jmx.JMXReporterActor.aroundReceive(JMXReporterActor.scala:187)
[info] 	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:526)
[info] 	at akka.actor.ActorCell.invoke_aroundBody2(ActorCell.scala:495)
[info] 	at akka.actor.ActorCell$AjcClosure3.run(ActorCell.scala:1)
[info] 	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:229)
[info] 	at akka.dispatch.WeaveActorReceive.$anonfun$contextInvoke$1(ContextPropagatingDispatcher.scala:29)
[info] 	at mesosphere.marathon.core.async.package$.propagateContext(package.scala:15)
[info] 	at akka.dispatch.WeaveActorReceive.contextInvoke(ContextPropagatingDispatcher.scala:29)
[info] 	at akka.actor.ActorCell.invoke(ActorCell.scala:488)
[info] 	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
[info] 	at akka.dispatch.Mailbox.run(Mailbox.scala:224)
[info] 	at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
[info] 	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
[info] 	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
[info] 	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
[info] 	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

a metric included the `:` character. I think Kamon JMX should sanitize metric names before creating MBeans.

**Comment by egor-ryashin** [comment]
Just got the same exception.
